"""
分析阶段 v0.1：把 pipeline.py 提取出的结构化行项目，映射到统一 schema，
计算同比增速，并套用银行 / 硬件两组关注点框架生成表格+文字结论。

设计原则（对齐既定要求）：分析深度先做浅、做稳，不做过度推断；
凡是没有直接从数据算出来的判断（比如"好/坏"），只给数字和方向，
不替用户下结论。
"""
from extract import run_extraction

# ---- 字段映射：canonical_field -> 该行标签里必须包含的子串 ----
# 用"包含"匹配而不是精确匹配，因为解析出来的label有时会带上换行拼接的
# 页眉噪音前缀（如"2025年度...合并及公司利润表...利息净收入"）。
US_INCOME_MAP = {
    "revenue": "Total net sales",
    "cost_of_revenue": "Total cost of sales",
    "gross_profit": "Gross margin",
    "rd_expense": "Research and development",
    "operating_income": "Operating income",
    "net_income": "Net income",
    "eps_diluted": "Diluted",
}
US_BALANCE_MAP = {
    "cash_and_equivalents": "Cash and cash equivalents",
    "total_assets": "Total assets",
    "total_liabilities": "Total liabilities",
    "total_equity": "Total shareholders",
}
US_CASHFLOW_MAP = {
    "cash_from_operations": "Cash generated by operating activities",
    "cash_from_investing": "investing activities",  # matches both 10-K/10-Q wording variants
    "cash_from_financing": "financing activities",   # matches both 10-K/10-Q wording variants
    "capex": "Payments for acquisition of property",
}

CN_INCOME_MAP = {
    "net_interest_income": "利息净收入",
    "fee_and_commission_income": "手续费及佣金净收入",
    "revenue": "营业收入",
    "operating_income": "营业利润",
    "net_income_group": "净利润",
}
CN_BALANCE_MAP = {
    "cash_and_equivalents": "现金及存放中央银行款项",
    "total_assets": "资产总计",
    "total_liabilities": "负债合计",
    "total_equity": "股东权益合计",
}
CN_CASHFLOW_MAP = {
    "cash_from_operations": "经营活动产生的现金流量净额",
    "cash_from_investing": "投资活动产生的现金流量净额",
    "cash_from_financing": "筹资活动产生的现金流量净额",
}
HK_INCOME_MAP = {
    "revenue": "收入",
    "cost_of_revenue": "銷售成本",
    "gross_profit": "毛利",
    "rd_expense": "研發開支",
    "operating_income": "經營利潤",
    "net_income": "期間利潤",
    "eps_diluted": "攤薄",
}

CN_KEY_RATIOS_MAP = {
    "roa": "平均总资产回报率",
    "roe": "加权平均净资产收益率",
    "nim": "净利息收益率",
    "cost_to_income_ratio": "成本收入比",
    "npl_ratio": "不良贷款率",
    "provision_coverage_ratio": "拨备覆盖率",
    "car": "资本充足率(10)",
    "cet1": "核心一级资本充足率(10)",
}


def map_to_schema(items, field_map):
    """从 items 列表按子串匹配抽取 canonical 字段。
    按 needle 长度从长到短匹配（避免"资本充足率"这种短词被"核心一级资本
    充足率"这种包含它的长词行抢先命中），且每一行数据一旦被某个字段认领，
    就不能再被其他字段复用（避免两个字段指向同一行）。
    """
    out = {}
    used = set()
    for field, needle in sorted(field_map.items(), key=lambda kv: -len(kv[1])):
        for idx, it in enumerate(items):
            if idx in used:
                continue
            if needle in it["label"]:
                out[field] = {"label": it["label"][-40:], "values": it["values"]}
                used.add(idx)
                break
    # 按原始 field_map 顺序返回，而不是匹配顺序
    return {f: out[f] for f in field_map if f in out}


def pct_change(curr, prior):
    if prior in (None, 0):
        return None
    return round((curr - prior) / abs(prior) * 100, 2)


def build_schema(extraction, report_type):
    schema = {}
    if report_type in ("us_10k", "us_10q"):
        schema.update(map_to_schema(extraction["income_statement"]["items"], US_INCOME_MAP))
        schema.update(map_to_schema(extraction["balance_sheet"]["items"], US_BALANCE_MAP))
        schema.update(map_to_schema(extraction["cash_flow"]["items"], US_CASHFLOW_MAP))
    elif report_type == "cn_a_share_annual":
        schema.update(map_to_schema(extraction["income_statement"]["items"], CN_INCOME_MAP))
        schema.update(map_to_schema(extraction["balance_sheet"]["items"], CN_BALANCE_MAP))
        schema.update(map_to_schema(extraction["cash_flow"]["items"], CN_CASHFLOW_MAP))
        schema.update(map_to_schema(extraction["key_ratios"]["items"], CN_KEY_RATIOS_MAP))
    elif report_type == "hk_quarterly":
        schema.update(map_to_schema(extraction["income_statement"]["items"], HK_INCOME_MAP))
    return schema


def render_markdown_table(schema, report_type, company_label):
    """输出表格形式：字段 | 本期 | 上期 | 同比变化"""
    # 不同报告类型的期数排列约定不同,这里只取"本期 vs 可比上期"两个数
    period_idx = {"us_10k": (0, 1), "us_10q": (0, 1), "cn_a_share_annual": (0, 1), "hk_quarterly": (0, 1)}
    curr_i, prior_i = period_idx[report_type]
    lines = [f"### {company_label} 关键指标一览\n", "| 字段 | 本期 | 上期 | 同比 |", "|---|---|---|---|"]
    for field, data in schema.items():
        vals = data["values"]
        if len(vals) <= max(curr_i, prior_i):
            continue
        curr, prior = vals[curr_i], vals[prior_i]
        chg = pct_change(curr, prior)
        chg_str = f"{chg:+.1f}%" if chg is not None else "n/a"
        lines.append(f"| {field} | {curr:,.1f} | {prior:,.1f} | {chg_str} |")
    return "\n".join(lines)


def render_narrative(schema, report_type, company_label):
    """输出文档形式：用计算出的同比数字写成叙述段落。
    原则：只陈述数字和方向，不做"好/坏"这类主观判断，不做没有数据支撑的推测。
    """
    period_idx = {"us_10k": (0, 1), "us_10q": (0, 1), "cn_a_share_annual": (0, 1), "hk_quarterly": (0, 1)}
    curr_i, prior_i = period_idx[report_type]

    def g(field):
        d = schema.get(field)
        if not d or len(d["values"]) <= max(curr_i, prior_i):
            return None, None, None
        curr, prior = d["values"][curr_i], d["values"][prior_i]
        return curr, prior, pct_change(curr, prior)

    paras = [f"## {company_label} 财务概况\n"]

    if report_type in ("us_10k", "us_10q"):
        rev, _, rev_chg = g("revenue")
        ni, _, ni_chg = g("net_income")
        gp, _, gp_chg = g("gross_profit")
        rd, _, rd_chg = g("rd_expense")
        cfo, _, cfo_chg = g("cash_from_operations")
        capex, _, capex_chg = g("capex")
        paras.append(
            f"营收 {rev:,.0f} 百万美元，同比{'增长' if rev_chg and rev_chg>0 else '下降'} "
            f"{abs(rev_chg):.1f}%；净利润 {ni:,.0f} 百万美元，同比"
            f"{'增长' if ni_chg and ni_chg>0 else '下降'} {abs(ni_chg):.1f}%，"
            f"增速{'快于' if ni_chg and rev_chg and ni_chg>rev_chg else '慢于'}营收增速，"
            f"说明净利润变化中包含营收之外的因素（毛利率、费用率或非经营性项目）。"
        )
        paras.append(
            f"毛利 {gp:,.0f} 百万美元，同比{gp_chg:+.1f}%；研发费用 {rd:,.0f} 百万美元，"
            f"同比{rd_chg:+.1f}%。"
        )
        paras.append(
            f"经营活动现金流净额 {cfo:,.0f} 百万美元，同比{cfo_chg:+.1f}%；"
            f"资本开支 {abs(capex):,.0f} 百万美元，同比{'增加' if capex_chg and capex_chg<0 else '减少'}"
            f"{abs(capex_chg):.1f}%（capex以负值记录，负值扩大代表投入增加）。"
        )
    elif report_type == "cn_a_share_annual":
        nii, _, nii_chg = g("net_interest_income")
        rev, _, rev_chg = g("revenue")
        ni, _, ni_chg = g("net_income_group")
        nim_curr, nim_prior, nim_chg = g("nim")
        npl_curr, npl_prior, npl_chg = g("npl_ratio")
        cov_curr, cov_prior, cov_chg = g("provision_coverage_ratio")
        car_curr, car_prior, car_chg = g("car")
        roe_curr, roe_prior, roe_chg = g("roe")
        paras.append(
            f"营业收入 {rev:,.0f} 百万元，同比{rev_chg:+.1f}%；其中利息净收入 "
            f"{nii:,.0f} 百万元，同比{nii_chg:+.1f}%。归母净利润同比{ni_chg:+.1f}%。"
        )
        paras.append(
            f"净息差(NIM) {nim_curr:.2f}%，去年同期{nim_prior:.2f}%"
            f"（{'走阔' if nim_chg and nim_chg>0 else '收窄'}），"
            f"净利息收入同比{'增长' if nii_chg and nii_chg>0 else '下降'}"
            f"{abs(nii_chg):.1f}%，与净息差方向"
            f"{'一致' if (nii_chg and nim_chg and nii_chg*nim_chg>0) else '不完全一致（可能由生息资产规模变化对冲）'}。"
        )
        paras.append(
            f"资产质量：不良贷款率 {npl_curr:.2f}%（去年同期{npl_prior:.2f}%），"
            f"拨备覆盖率 {cov_curr:.1f}%（去年同期{cov_prior:.1f}%）。"
        )
        paras.append(
            f"资本充足率 {car_curr:.2f}%（去年同期{car_prior:.2f}%）；"
            f"加权平均净资产收益率(ROE) {roe_curr:.2f}%（去年同期{roe_prior:.2f}%）。"
        )
    return "\n\n".join(paras)


if __name__ == "__main__":
    for path, rtype, label in [
        ("_10-K-2025-As-Filed.pdf", "us_10k", "Apple FY2025 10-K"),
        ("2025AnnualReportA.pdf", "cn_a_share_annual", "工商银行 FY2025 年报"),
    ]:
        extraction = run_extraction(path, rtype)
        schema = build_schema(extraction, rtype)
        print(render_markdown_table(schema, rtype, label))
        print()
        print(render_narrative(schema, rtype, label))
        print("\n" + "="*60 + "\n")
